// <auto-generated />
namespace StudentPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Course_and_courseenrollment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_and_courseenrollment));
        
        string IMigrationMetadata.Id
        {
            get { return "202402080009047_Course_and_courseenrollment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
